version: '3.6'

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=transactionsdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    restart: always
  web:
    build: .
    command: flask run -h 0.0.0.0
    volumes:
      - ./:/usr/src/app/
    ports:
      - "5000:5000"
    environment:
      - POSTGRES_DB=transactionsdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
    restart: always
volumes:
  postgres_data: